language: node_js
sudo: false
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
install:
  - yarn
script:
  - yarn test
  - yarn cov
after_success:
  - bash <(curl -s https://codecov.io/bash)
