language: node_js
sudo: false
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
install:
  - npm install
  - npm install -g istanbul
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/jasmine/bin/jasmine.js
